### ISSUE TITLE
Feature: automatic output encoding

### ISSUE THREAD

**Issue by kamstrup** [kamstrup/command_runner_ng#12]
We've seen several issues where you receive output with utf-8 encoding errors from what ever tool you invoke. Each CommandRunner.run callsite has to implement specific handling of this. CommandRunner should help with this!

The classic Ruby code to do error correction of bad UTF-8 looks somewhat like
```rb
output.encode('UTF-8', {
            :invalid => :replace,
            :undef   => :replace,
            :replace => '?'
        })
```

API Proposal:
Add a new keyword `encode` to the CommandRunner.run method that defaults to `nil`. If set to `:safe` it'll use a default encoding on the output looking like the above. If it is set to a Hash, the output will be passed through the call

```
output.encode('UTF-8', the_hash_here)
```

Example:
```
my_safe_result = CommandRunner.run('ls /tmp', encode: :safe)
```

When creating instances of the command runner it should also be possible to store the encoding setting. This code is identical to the previous example:
```rb
ls = CommandRunner.create(['ls'], encode: :safe)
my_safe_result =  ls.run('/tmp')
```

**Comment by jmoody** [comment]
I think `UTF-8` is a reasonable value for `:safe`.  

Do we want to support other encodings?   Or is this beyond the scope of work?

```
CommandRunner.run('ls /tmp', encode: "UTF-16")

ls = CommandRunner.create(['ls'], encode: "UTF-16")
my_safe_result =  ls.run('/tmp')
```

**Comment by jmoody** [comment]
ATTN: @owenniblock

**Comment by jmoody** [comment]
I believe I have seen examples where `encode` might fail to produce a string that responds to`.valid_encoding?` with `true`.  Any thoughts about whether we want to raise an error in that case?

Looking at the RunLoop code now, it is possible that RunLoop is overly defensive about detecting failures.  I do have some real-world fixtures that demonstrate several failure cases.

**Comment by owenniblock** [comment]
I feel like we should be supporting other encoding - if this is a library it should be as generic as we can make it.

> Any thoughts about whether we want to raise an error in that case?
I think we should be raising an error in this instance. It'll be easier to identify where errors are coming from if we raise them from the source rather than later when the string is used.

**Comment by kamstrup** [comment]
Yeah, I gave it some thought about != utf-8 encodings; just couldn't come up with a nice way to express it in the API... In the last 10 years of programming I've not personally had a valid reason for encoding in anything other than utf-8, so I guess the demand for it is going to be small :-)

That said we could allow for passing a closure as `:encode` option, in which case we simply invoke the encode closure on `result[:out]` (and `result[:err]` if it's there). But not super happy about this, as I really want to leave the door open for doing streaming encoding under the hood, not having the API force us to copy the stdout in memory (it might be huge).

We might also want to add an option for setting a global state, like we do for the debug logger: https://github.com/kamstrup/command_runner_ng/blob/master/lib/command_runner.rb#L191-L199

**Comment by kamstrup** [comment]
Ok. Here's what the ideal solution would be:

You can set `:encode` to `:safe` or an instance of `Encoding::Converter` (see https://ruby-doc.org/core-2.2.0/Encoding/Converter.html).

Internally we *stream* stdout/stderr through this encoder.

 * No copies of (possibly) huge buffers
 * Full support for any old encoding supported by Ruby

**Comment by kamstrup** [comment]
Thanks for your work and input @jmoody and @owenniblock ! I just merged https://github.com/kamstrup/command_runner_ng/pull/13 and command runner ng 0.1.4 is released!
