### ISSUE TITLE
Add options for not merging stderr/stdout in run()

### ISSUE THREAD

**Issue by kamstrup** [kamstrup/command_runner_ng#3]
See bug title

**Comment by jmoody** [comment]
I think this will be useful, especially when dealing with Xcode beta tools.

Also, Xcode's instruments command is prone to spewing many lines of stderr which are ignorable, but would need to be accounted for when parsing the output of `xcrun instruments -s devices`.

**Comment by kamstrup** [comment]
Others have expressed interest as well. Bumped this one to the top of my todo.

**Comment by jmoody** [comment]
@kamstrup 

I just bumped into problem with merged stderr and stdout.

`xcrun simctl list device --json` is printing JSON to stdout and some meaningless warnings/errors to stderr.

Looking at [the source](https://github.com/kamstrup/command_runner_ng/blob/master/lib/command_runner.rb#L71) it does not look that easy to make this change.  IO.popen only returns one IO object.  Am I missing something?  Can we switch over to popen3?

**Comment by kamstrup** [comment]
IIRC you can supply stream mapping to IO.popen()... I think that was the way I originally envisioned it...

**Comment by krukow** [comment]
https://ruby-doc.org/stdlib-2.3.3/libdoc/open3/rdoc/Open3.html#method-c-popen3

**Comment by krukow** [comment]
although there is this... which I'm not sure about:

```
In addition, a thread to wait for the started process is created. 
The thread has a pid method and a thread variable :pid which 
is the pid of the started process.
```

**Comment by kamstrup** [comment]
I have the 0.1.1 bagged and tagged with this fix, only problem is that I can't log in to my rubygems account to publish it X-)

Getting it sorted out and closing this issues once it's resolved.

**Comment by kamstrup** [comment]
0.1.1 pushed to rybygems!
