### ISSUE TITLE
Raise an error indicating the command exceeded the timeout.

### ISSUE THREAD

**Issue by jmoody** [kamstrup/command_runner_ng#4]
It would be helpful for clients to be able to rescue timeout errors so:
1. retries could be attempted
2. meaningful errors could be presented to the user

**Comment by kamstrup** [comment]
There is some support for this - not sure if it applies to everything you need. The way it is currently intended to work is like this:

``` rb
begin
  CommandRunner.run('sleep 2', timeout: { 1 => Proc.new {|pid| raise "Timed out"}})
rescue
  do_the_retry_dance
end
```

**Comment by jmoody** [comment]
Ah.  So the Proc should raise the error.

I settled on checking the `[:process_status].exitcode` after execution.  If it is `nil`, then I know the command timed out.

Will this Proc:

```
Proc.new {|pid| raise "Timed out"}}
```

also send kill to the command?  Asked another way, if pass a Proc, does it need to kill the process?

**Comment by kamstrup** [comment]
Yes; if the timeout proc raises the child will get a kill -9 and the
exception propagated to the caller of run().
