### ISSUE TITLE
Allow debug printing

### ISSUE THREAD

**Issue by sapieneptus** [kamstrup/command_runner_ng#9]
# Motivation

It would be great if we had a mode where we could get some console output of what command is being run. In some contexts it's common enough to need this info for debugging that it would be nice if `CommandRunner` had a built in option or static mode for doing so. 

Normally I'd do something like this:

```ruby
def shell(args)
    puts "EXEC: #{args}" if verbose_mode?
    out = CommandRunner.run(args)[:out]    
    puts "RESULT: #{out}" if verbose_mode?
    out
end
```

Perhaps instead there could be a static flag:
```ruby
CommandRunner.enable_debug_log
```

Or an option passed to commands:
```ruby
CommandRunner.run(args, :debug_log => true)
```

**Comment by kamstrup** [comment]
I think the idea is great. This is something that I also find a recurring theme in debugging.

There are a few things to consider though:
 - There is an instanced CommandRunner as well, providing a nice way to work with tools with sub-commands ala git and adb. Instances of CommandRunners should probably have a locally defined debug behavior.
 - Which stream does the debug info go to? Maybe the debug_log could point at any old IO object and we end the log there.
